#ifndef __DEFINES_H__
#define __DEFINES_H__

#define WRITEBYTE(WORD,BITSTARTPOS,BYTE) WORD=((WORD&~(0xFF<<BITSTARTPOS))|(BYTE<<BITSTARTPOS))

#define READBIT(WORD,BIT) ((WORD>>BIT)&1)

#define WRITEBIT(WORD,BITPOS,BITLEVEL) WORD=((WORD&~(1<<BITPOS))|(BITLEVEL<<BITPOS))

#define SETBIT(WORD,BIT) (WORD|=(1<<BIT))

#define CLRBIT(WORD,BIT) (WORD&=~(1<<BIT))

#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#endif
